import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useRouter } from 'next/router'
import Link from 'next/link'
export default function Home() {
  const router = useRouter();

  const handle = () => {
    router.push('/route');
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href='/route'>
          <button>direct to route</button>
        </Link>

        <button onClick={handle}>onClick to route</button>
      </main>
    </div>
  )
}
